services:
  - type: web
    name: covid-economic-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 